In [1]:
import torch

In [25]:
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.5129, 0.7992, 0.4017], requires_grad=True)


In [33]:
y = x**2
print(y)

tensor([0.2631, 0.6387, 0.1613], grad_fn=<PowBackward0>)


In [42]:
y = y.mean()
print(y)

tensor(0.3544, grad_fn=<MeanBackward0>)


In [45]:
#y.backward()

In [44]:
print(x.grad)

tensor([1.3420, 1.5328, 1.2678])


## Back propagation

In [46]:
import torch

In [48]:
x = torch.tensor([2],  dtype=torch.float32)
y = torch.tensor([3] , dtype=torch.float32)
w = torch.tensor(1.0, requires_grad=True)

In [49]:
y_hat = w*x
s = y_hat - y
loss = s**2
print(loss)

tensor([1.], grad_fn=<PowBackward0>)


In [50]:
#backward pass
loss.backward()
print(w.grad)

tensor(-4.)


### Gradient Descent

In [77]:
import torch
import torch.nn as nn

In [90]:
X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

In [91]:
print(X.shape)

torch.Size([4, 1])


In [104]:
X_test = torch.tensor([5], dtype=torch.float32)
n_samples, n_features = X.shape
print(n_samples, n_features)
input_size = n_features
output_size = n_features
model = nn.Linear(input_size,output_size)

print(f'Prediction before training : f(5)= {model(X_test).item():.3f}')
#Training
learning_rate = 0.01
n_iters = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = model(X)
    #loss
    l = loss(Y,y_pred)
    #gradient
    l.backward() #dl/dw
    #update gradient
    optimizer.step()
    #zero grad
    optimizer.zero_grad()
    if epoch%10 ==0:
        [w, b] = model.parameters()
        print(f'epoch {epoch+1}: w= {w[0][0].item():.3f}, loss = {l:.8f}')
print(f'Prediction after training : f(5)= {model(X_test).item():.3f}')

4 1
Prediction before training : f(5)= 2.810
epoch 1: w= 0.803, loss = 15.83829594
epoch 11: w= 1.717, loss = 0.42641872
epoch 21: w= 1.867, loss = 0.02670779
epoch 31: w= 1.893, loss = 0.01545392
epoch 41: w= 1.900, loss = 0.01430345
epoch 51: w= 1.904, loss = 0.01346444
epoch 61: w= 1.907, loss = 0.01268054
epoch 71: w= 1.909, loss = 0.01194249
epoch 81: w= 1.912, loss = 0.01124737
epoch 91: w= 1.915, loss = 0.01059272
Prediction after training : f(5)= 9.829
